services:
  postgres:
    container_name: 'ms_booking'
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=booking'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
